from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

STATE_DIRECTORY = ".wiki-state"
SOURCES_FILENAME = "sources.json"
INGEST_HISTORY_FILENAME = "ingest-history.jsonl"
LLM_CACHE_FILENAME = "llm-cache.json"
SCHEMA_VERSION = 1


@dataclass(frozen=True)
class StorageState:
    """Paths for MemoWeaver's file-based state store.

    The state store intentionally lives inside the wiki directory instead of a
    user-level cache. A wiki should be portable: if a user copies the wiki to a
    different machine, MemoWeaver can still know which sources were seen, which
    content hashes were already registered, and which future LLM calls may be
    reused. Phase 2 keeps this as plain JSON/JSONL so contributors can inspect
    and edit the files without needing a database client.
    """

    wiki_path: Path
    state_path: Path
    sources_path: Path
    ingest_history_path: Path
    llm_cache_path: Path


@dataclass(frozen=True)
class SourceRecord:
    """A durable entry in the source registry.

    `source_id` is derived from the content hash, not the file path. This makes
    duplicate detection work even when the same document appears under two
    filenames. `uri` preserves where the current sighting came from; later
    ingestion work can extend this model with additional sightings if needed.
    """

    source_id: str
    uri: str
    kind: str
    sha256: str
    title: str | None
    first_seen_at: str
    last_seen_at: str
    ingest_count: int
    metadata: dict[str, Any]

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SourceRecord":
        return cls(
            source_id=str(data["source_id"]),
            uri=str(data["uri"]),
            kind=str(data["kind"]),
            sha256=str(data["sha256"]),
            title=data.get("title"),
            first_seen_at=str(data["first_seen_at"]),
            last_seen_at=str(data["last_seen_at"]),
            ingest_count=int(data.get("ingest_count", 1)),
            metadata=dict(data.get("metadata", {})),
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "source_id": self.source_id,
            "uri": self.uri,
            "kind": self.kind,
            "sha256": self.sha256,
            "title": self.title,
            "first_seen_at": self.first_seen_at,
            "last_seen_at": self.last_seen_at,
            "ingest_count": self.ingest_count,
            "metadata": self.metadata,
        }


@dataclass(frozen=True)
class RegisterSourceResult:
    """Result returned by a source registration attempt."""

    record: SourceRecord
    created: bool


def initialize_state(wiki_path: str | Path) -> StorageState:
    """Create the minimal file-based storage layout for a wiki.

    Existing files are never overwritten. This mirrors `init_wiki()` and keeps
    user edits or state generated by earlier runs safe. The layout is deliberately
    small for the MVP:

    - `sources.json` stores the canonical source registry.
    - `ingest-history.jsonl` stores append-only events for audit/debugging.
    - `llm-cache.json` is only seeded here; later LLM work can define entries.
    """

    wiki = Path(wiki_path)
    state_path = wiki / STATE_DIRECTORY
    sources_path = state_path / SOURCES_FILENAME
    ingest_history_path = state_path / INGEST_HISTORY_FILENAME
    llm_cache_path = state_path / LLM_CACHE_FILENAME

    state_path.mkdir(parents=True, exist_ok=True)
    if not sources_path.exists():
        _write_json(sources_path, {"schema_version": SCHEMA_VERSION, "sources": []})
    if not ingest_history_path.exists():
        ingest_history_path.write_text("", encoding="utf-8")
    if not llm_cache_path.exists():
        _write_json(llm_cache_path, {"schema_version": SCHEMA_VERSION, "entries": {}})

    return StorageState(
        wiki_path=wiki,
        state_path=state_path,
        sources_path=sources_path,
        ingest_history_path=ingest_history_path,
        llm_cache_path=llm_cache_path,
    )


class LLMExtractionCache:
    """Read and write structured LLM extraction payloads.

    Cache entries are keyed by source id, model, and extraction schema version so
    MemoWeaver can reuse deterministic extraction results without hiding when a
    model/schema change should trigger a fresh call. The cache stores plain
    dictionaries to avoid coupling the storage layer to LLM provider classes.
    """

    def __init__(self, state: StorageState) -> None:
        self.state = state

    @classmethod
    def open(cls, wiki_path: str | Path) -> "LLMExtractionCache":
        return cls(initialize_state(wiki_path))

    def get(self, source_id: str, *, model: str, schema_version: int) -> dict[str, Any] | None:
        data = self._read_cache_document()
        entry = data.get("entries", {}).get(self.cache_key(source_id, model=model, schema_version=schema_version))
        if not isinstance(entry, dict):
            return None
        extraction = entry.get("extraction")
        return dict(extraction) if isinstance(extraction, dict) else None

    def put(self, extraction: Any, *, model: str, schema_version: int) -> dict[str, Any]:
        payload = extraction.to_dict() if hasattr(extraction, "to_dict") else dict(extraction)
        source_id = str(payload.get("source_id") or "")
        if not source_id:
            raise ValueError("Cached extraction payload must include source_id")
        data = self._read_cache_document()
        entries = dict(data.get("entries", {}))
        entries[self.cache_key(source_id, model=model, schema_version=schema_version)] = {
            "schema_version": SCHEMA_VERSION,
            "source_id": source_id,
            "model": model,
            "extraction_schema_version": schema_version,
            "cached_at": _utc_now(),
            "extraction": payload,
        }
        _write_json(self.state.llm_cache_path, {"schema_version": SCHEMA_VERSION, "entries": entries})
        return payload

    @staticmethod
    def cache_key(source_id: str, *, model: str, schema_version: int) -> str:
        return f"{source_id}::{model}::schema-{schema_version}"

    def _read_cache_document(self) -> dict[str, Any]:
        return json.loads(self.state.llm_cache_path.read_text(encoding="utf-8"))


class SourceRegistry:
    """Read and write MemoWeaver's source registry.

    The registry is intentionally tiny, synchronous, and file-based. That keeps
    the early project easy to understand for open-source contributors. If the
    registry later outgrows JSON, this class becomes the seam where a SQLite
    backend can be introduced without changing ingest code.
    """

    def __init__(self, state: StorageState) -> None:
        self.state = state

    @classmethod
    def open(cls, wiki_path: str | Path) -> "SourceRegistry":
        return cls(initialize_state(wiki_path))

    def list_sources(self) -> list[SourceRecord]:
        data = self._read_sources_document()
        return [SourceRecord.from_dict(item) for item in data.get("sources", [])]

    def find_by_sha256(self, sha256: str) -> SourceRecord | None:
        for record in self.list_sources():
            if record.sha256 == sha256:
                return record
        return None

    def register_file(
        self,
        source_path: str | Path,
        *,
        kind: str = "file",
        title: str | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> RegisterSourceResult:
        """Register a local file by content hash.

        Registering is not the same as ingesting. Phase 2 only records identity
        and repeat sightings; Phase 3 can call this method before copying raw
        sources or parsing Markdown. This separation prevents the ingestion
        pipeline from owning duplicate-detection logic.
        """

        path = Path(source_path)
        content_hash = sha256_file(path)
        uri = path.expanduser().resolve().as_uri()
        now = _utc_now()
        data = self._read_sources_document()
        records = [SourceRecord.from_dict(item) for item in data.get("sources", [])]

        for index, record in enumerate(records):
            if record.sha256 == content_hash:
                updated = SourceRecord(
                    source_id=record.source_id,
                    uri=record.uri,
                    kind=record.kind,
                    sha256=record.sha256,
                    title=record.title,
                    first_seen_at=record.first_seen_at,
                    last_seen_at=now,
                    ingest_count=record.ingest_count + 1,
                    metadata=record.metadata,
                )
                records[index] = updated
                self._write_sources(records)
                self._append_history("source_seen", updated, observed_uri=uri)
                return RegisterSourceResult(record=updated, created=False)

        record = SourceRecord(
            source_id=source_id_for_sha256(content_hash),
            uri=uri,
            kind=kind,
            sha256=content_hash,
            title=title,
            first_seen_at=now,
            last_seen_at=now,
            ingest_count=1,
            metadata=dict(metadata or {}),
        )
        records.append(record)
        self._write_sources(records)
        self._append_history("source_registered", record, observed_uri=uri)
        return RegisterSourceResult(record=record, created=True)

    def _read_sources_document(self) -> dict[str, Any]:
        return json.loads(self.state.sources_path.read_text(encoding="utf-8"))

    def _write_sources(self, records: list[SourceRecord]) -> None:
        _write_json(
            self.state.sources_path,
            {
                "schema_version": SCHEMA_VERSION,
                "sources": [record.to_dict() for record in records],
            },
        )

    def _append_history(self, event: str, record: SourceRecord, *, observed_uri: str) -> None:
        # JSONL gives us an append-only audit trail without rewriting a large
        # history file. Each line stands alone, which is useful for debugging
        # failed future ingestion jobs.
        payload = {
            "schema_version": SCHEMA_VERSION,
            "event": event,
            "source_id": record.source_id,
            "sha256": record.sha256,
            "uri": record.uri,
            "observed_uri": observed_uri,
            "occurred_at": record.last_seen_at,
        }
        with self.state.ingest_history_path.open("a", encoding="utf-8") as handle:
            handle.write(json.dumps(payload, ensure_ascii=False, sort_keys=True) + "\n")


def sha256_file(path: str | Path) -> str:
    """Return the SHA-256 digest for a file without loading it all at once."""

    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def source_id_for_sha256(sha256: str) -> str:
    """Create a short stable source id from a full SHA-256 digest."""

    return f"src_{sha256[:16]}"


def _write_json(path: Path, data: dict[str, Any]) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")
